name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  IMAGE_NAME: djhofmann/rpiplay
  IMAGE_TAG:  latest

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_NAME:$IMAGE_TAG
  
  push:
    runs-on: ubuntu-latest
    steps:
      - name: Login
        run: docker login -u ${{ secrets.DOCKER_HUB_USERNAME}} -p ${{ secrets.DOCKER_HUB_PASSWORD }}
      - name: Push
        run: docker push $IMAGE_NAME:$IMAGE_TAG
        
        
